<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Main extends CI_Controller {
	function Main(){
		parent::__construct();
		$this->load->model('users');
		$this->load->model('questions');	
	}
	public function index(){	
		if($this->session->userdata('is_logged_in')){
			$this->logged_in();
		}
		else {
			echo "You have no authorisation to be on this page";
		}		
	}
	function logged_in(){
		if($this->session->userdata('is_logged_in')){
			$taken_quiz = $this->session->userdata('taken_quiz');
			$username = $this->session->userdata('username');
			$this->_user_load_Home($taken_quiz);			
		}
		else {
			echo "You no longer have permission to view this page.";
			echo "<a href='../home_controller/index'>Go back</a>";
			die();
		}
	}
	function logged_out(){
		$this->session->unset_userdata('username');
		$this->session->unset_userdata('is_logged_in');
		$this->session->unset_userdata('taken_quiz');
		$this->session->sess_destroy();
		redirect(base_url());
		
	}
	function _user_load_home($taken_quiz){
		$title = "Soft Skills Development";
		if($taken_quiz === 1){
			redirect('main/viewScore');
		}
		else{
			redirect('main/viewQuestion');
		}
	}
	function viewQuestion(){
		if($this->session->userdata('is_logged_in')){
			$data_load= array(
				'title' => $this->session->userdata('username'),
				'questions' => $this->questions->getQuestions(),
				'q_total' => $this->questions->getNumber()
				);
			$this->load->view('home',$data_load);
			$this->load->view('navbar',$data_load);
			$this->load->view('question',$data_load);
			$this->load->view('footer');	
		}else{
			echo "You no longer have permission to view this page.";
			echo "<a href='../home_controller/index'>Go back</a>";
		}	
	}
	function score(){
		$username = $this->session->userdata('username');
		$result = array();
		$sum_sh = 0;
		$sum_r = 0;
		$sum_c = 0;
		$sum_g = 0;
		$sum_d = 0;		
		for($i=1;$i<=50;$i++){
			$st= "q_".$i;
			$result[$i] = $this->input->post($st);
		}
		for($i=1;$i<=6;$i++){
			$sum_sh = $sum_sh+ $result[$i]; //sum of inputs for stress handling
		}
		for($i=7;$i<=12;$i++){
			$sum_r = $sum_r+ $result[$i]; //sum of inputs for responsiveness
		}
		for($i=13;$i<=18;$i++){
			$sum_c = $sum_c+ $result[$i]; //sum of inputs for communication
		}
		for($i=19;$i<=24;$i++){
			$sum_g = $sum_g+ $result[$i]; //sum of inputs for grooming
		}
		for($i=25;$i<=30;$i++){
			$sum_d = $sum_d+ $result[$i]; //sum of inputs for delegation
		}
		$data = array(
			'taken_quiz' =>1,
			'stress_handling' => $sum_sh,
			'responsiveness' => $sum_r,
			'communication' =>$sum_c,
			'grooming' => $sum_g,
			'delegation' =>$sum_d,
			'total' => $sum_sh+$sum_r+$sum_c+$sum_g+$sum_d,
			'date' => date('Y-m-d')
			);
		$c1 = $this->users->setSurvey($data,$username);
		if($c1){
			$message = "Dear HR, <br><br>The result of the Soft Skills Development Quiz undertaken by the user ".$username." is as follows- <br><br>"
			 ."<b>Stress Handling:</b>".$this->generateReport($sum_sh)."<br><b>Responsiveness:</b>".$this->generateReport($sum_r)."<br><b>Communication:</b>".$this->generateReport($sum_c)."<br><b>Grooming:</b>".$this->generateReport($sum_g)."<br><b>Delegation:</b>".$this->generateReport($sum_d)."<br>"
			 ."This is for your kind information.<br><br>(This is an autogenerated email. Please do not respond back to this mail.Thank you)";
			$this->sendMail($message,$username);
			redirect('main/viewScore');
		}
	}
	function viewScore(){
		if($this->session->userdata('is_logged_in')){
			$user = $this->session->userdata('username');
				$title = "Welcome ".$user;
				$data = array(
				'title' => $title,
				'stress_handling' => $this->users->fetchData('stress_handling',$user)[0]['stress_handling'],
				'responsiveness' => $this->users->fetchData('responsiveness',$user)[0]['responsiveness'],
				'communication' =>$this->users->fetchData('communication',$user)[0]['communication'],
				'grooming' => $this->users->fetchData('grooming',$user)[0]['grooming'],
				'delegation' =>$this->users->fetchData('delegation',$user)[0]['delegation'],
				'total' => $this->users->fetchData('total',$user)[0]['total'],
				'date' => $this->users->fetchData('date',$user)[0]['date']
				);
				$this->load->view('home',$data);
				$this->load->view('navbar',$data);
				$this->load->view('scorecard',$data);
				$this->load->view('footer');
		}
		else{
			echo "You no longer have permission to view this page.";
			echo "<a href='../home_controller/index'>Go back</a>";
		}
	}
	function new_test(){
		redirect('main/viewQuestion');
	}
	function sendMail($message,$username){
		$config = Array(
			'protocol' => 'smtp',
			'smtp_host' => 'ssl://smtp.googlemail.com',
			'smtp_port' => 465,
			'smtp_user' => 'ssdamitydrexel@gmail.com', //change it to the new email server address provided
			'smtp_pass' => 'softskills', // change it to the relevant password
			'mailtype' => 'html',
			'charset' => 'iso-8859-1',
			'wordwrap' => TRUE
			);
		$this->load->library('email', $config);
		$this->email->set_newline("\r\n");
		$this->email->from('ssdamitydrexel@gmail.com'); // change it to the new email address provided
		$this->email->to('hr@vervesys.com');// The HR email address for Verve Systems goes here
		$this->email->cc($username);
		$this->email->subject('Result of Soft Skills Quiz');
		$this->email->message($message);
		if($this->email->send()){
			//Do nothing
		}else{
		   	show_error($this->email->print_debugger());
		}
	}
	function between($min,$max,$input){return (($input>$min)&&($input<=$max))?true:false;}
	function test($c1,$c2,$c3){return $c1 ?"Performance was beyond expectations.":($c2 ? "Performance met expectations.":($c3 ? "Training recommended":"TRAINING MANDATED"));}	
	function generateReport($score){return $this->test($this->between(5.16,6,$score),$this->between(3.75,5.16,$score),$this->between(2.34,3.75,$score));}	
}
